### ISSUE TITLE
Mejorar mensajes de commits, y granularidad

### ISSUE THREAD

**Issue by delucas** [Lospioladeprogra/jrpg#3]
Un `agregado de código masivo` no ayuda a los desarrolladores a entender qué fue sucediendo en el proyecto.
Mejorar los mensajes en los commits, de ahora en más. Yo mismo cierro este issue cuando considere que lo mejoraron. Avísenme así lo reviso.

**Comment by nico2017** [comment]
Ya subi una actualizacion del proyecto profe. Asi estaria correcto?. puse en el mensaje algo concreto y en la descripcion con el gitKraken le especifique un poco mas.

**Comment by delucas** [comment]
Mejor, pero no repitas mensajes... seguramente se puede especificar mejor lo que se hizo.
Lo cierro, pero tenelo en cuenta.
